#!/bin/bash

PYTHON=python3
ENCRYPT_ME=./encrypt-me.py

function check_package {
    if ! $PYTHON -c "import $1" &> /dev/null; then
        echo "$1 not found, installing..."
        pip3 install "$1"
    fi
}

check_package cryptography
check_package requests

$PYTHON $ENCRYPT_ME "$@"