class ExitCodes:
    GOOD = 0
    INVALID_EMAIL = 1
    NO_MESSAGE_TO_ENCRYPT = 2
    REGISTRATION_FAILED = 10
    VALIDATION_FAILED = 11
    PASSWORDS_DO_NOT_MATCH = 12
    INVALID_PASSWORD = 13
    NOT_KEYS = 14
    UNKNOWN_ERROR = 100
